const GIGA_CATEGORIES = {
  SOCIAL_MEDIA: 'SOCIAL_MEDIA',
  PRODUCT_REVIEW: 'PRODUCT_REVIEW',
  UNBOXING: 'UNBOXING',
  TUTORIAL: 'TUTORIAL',
  SPONSORSHIP: 'SPONSORSHIP',
  BRAND_AMBASSADOR: 'BRAND_AMBASSADOR',
  CONTENT_CREATION: 'CONTENT_CREATION',
  PHOTOGRAPHY: 'PHOTOGRAPHY',
  VIDEOGRAPHY: 'VIDEOGRAPHY',
  OTHER: 'OTHER'
};

const GIG_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const CATEGORY_LABELS = {
  SOCIAL_MEDIA: 'Social Media Content',
  PRODUCT_REVIEW: 'Product Review',
  UNBOXING: 'Unboxing Video',
  TUTORIAL: 'Tutorial/How-To',
  SPONSORSHIP: 'Sponsored Content',
  BRAND_AMBASSADOR: 'Brand Ambassador',
  CONTENT_CREATION: 'Content Creation',
  PHOTOGRAPHY: 'Photography',
  VIDEOGRAPHY: 'Videography',
  OTHER: 'Other'
};

module.exports = {
  GIGA_CATEGORIES,
  GIG_STATUS,
  CATEGORY_LABELS
};
